### ISSUE TITLE
About the “id_name_conversion”

### ISSUE THREAD

**Issue by Dadiziji** [pykao/Modified-3D-UNet-Pytorch#1]
Thanks for your code and I have a problem.
When I run the N4ITKforBRATS2017.py，I got an error :/traindata/id name conversion.txt not found. What is the content of this txt file?

**Comment by pykao** [comment]
This file contains the conversion between a subject's name and his fake ID which is assigned by us. 

In order to create the file id_name_conversion.txt, you have to run the preprocessing(https://github.com/pykao/Modified-3D-UNet-Pytorch/blob/master/run_preporcessing.py) first. It will give you this file. 

This is an ongoing work. We will release the training part and data loading part after the BraTS 2018 challenge. The model.py works for sure. 

Best,
Po-Yu

**Comment by pykao** [comment]
This file contains the conversion between a subject's name and his fake ID which is assigned by us.
